version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: shopdjango-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopdjango
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: shopdjango-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    environment:
      POSTGRES_DB: shopdjango
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: shopdjango-db
      POSTGRES_PORT: 5432
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: