version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: shopdjango-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopdjango
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shopdjango-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: shopdjango-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"  # API endpoint
      - "9001:9001"  # Console UI
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  web:
    build: .
    container_name: shopdjango-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    environment:
      POSTGRES_DB: shopdjango
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: shopdjango-db
      POSTGRES_PORT: 5432
      DEBUG: "True"
      CELERY_BROKER_URL: redis://shopdjango-redis:6379/0
      CELERY_RESULT_BACKEND: redis://shopdjango-redis:6379/1
      SIMULATOR_PUSH_RELAY_URL: http://host.docker.internal:5055/notify
      # MinIO settings
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_S3_ENDPOINT_URL: http://shopdjango-minio:9000
      AWS_STORAGE_BUCKET_NAME: product-images
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - celery-worker

  celery-worker:
    build: .
    container_name: shopdjango-celery-worker
    command: celery -A shopdjango worker --loglevel=INFO
    volumes:
      - ./src:/app/src
    environment:
      POSTGRES_DB: shopdjango
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: shopdjango-db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://shopdjango-redis:6379/0
      CELERY_RESULT_BACKEND: redis://shopdjango-redis:6379/1
      SIMULATOR_PUSH_RELAY_URL: http://host.docker.internal:5055/notify
    depends_on:
      - db
      - redis


volumes:
  pgdata:
  minio-data: