# Generated by Django 5.2.3 on 2025-07-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='notes',
        ),
    ]
