# Generated by Django 5.2.4 on 2025-09-05 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_profile_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoleAssignment",
        ),
    ]
