/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfilesIndexRouteImport } from './routes/_authenticated/profiles/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedInvoiceTemplatesIndexRouteImport } from './routes/_authenticated/invoice-templates/index'
import { Route as AuthenticatedCountriesIndexRouteImport } from './routes/_authenticated/countries/index'
import { Route as AuthenticatedAddressesIndexRouteImport } from './routes/_authenticated/addresses/index'
import { Route as AuthenticatedInvoiceTemplatesNewRouteImport } from './routes/_authenticated/invoice-templates/new'
import { Route as AuthenticatedCountriesNewRouteImport } from './routes/_authenticated/countries/new'
import { Route as AuthenticatedAddressesNewRouteImport } from './routes/_authenticated/addresses/new'
import { Route as AuthenticatedOrdersOrderIdIndexRouteImport } from './routes/_authenticated/orders/$orderId/index'
import { Route as AuthenticatedNotificationsPreferencesIndexRouteImport } from './routes/_authenticated/notifications/preferences/index'
import { Route as AuthenticatedNotificationsHistoryIndexRouteImport } from './routes/_authenticated/notifications/history/index'
import { Route as AuthenticatedCheckoutShippingMethodsIndexRouteImport } from './routes/_authenticated/checkout/shipping-methods/index'
import { Route as AuthenticatedCheckoutShipmentsIndexRouteImport } from './routes/_authenticated/checkout/shipments/index'
import { Route as AuthenticatedCheckoutPaymentsIndexRouteImport } from './routes/_authenticated/checkout/payments/index'
import { Route as AuthenticatedCheckoutOrderNotesIndexRouteImport } from './routes/_authenticated/checkout/order-notes/index'
import { Route as AuthenticatedCheckoutInvoicesIndexRouteImport } from './routes/_authenticated/checkout/invoices/index'
import { Route as AuthenticatedCheckoutCouriersIndexRouteImport } from './routes/_authenticated/checkout/couriers/index'
import { Route as AuthenticatedCheckoutCouponsIndexRouteImport } from './routes/_authenticated/checkout/coupons/index'
import { Route as AuthenticatedCheckoutCouponRedemptionsIndexRouteImport } from './routes/_authenticated/checkout/coupon-redemptions/index'
import { Route as AuthenticatedCatalogTagsIndexRouteImport } from './routes/_authenticated/catalog/tags/index'
import { Route as AuthenticatedCatalogSuppliersIndexRouteImport } from './routes/_authenticated/catalog/suppliers/index'
import { Route as AuthenticatedCatalogProductsIndexRouteImport } from './routes/_authenticated/catalog/products/index'
import { Route as AuthenticatedCatalogManufacturersIndexRouteImport } from './routes/_authenticated/catalog/manufacturers/index'
import { Route as AuthenticatedCatalogDeliveriesIndexRouteImport } from './routes/_authenticated/catalog/deliveries/index'
import { Route as AuthenticatedCatalogCategoriesIndexRouteImport } from './routes/_authenticated/catalog/categories/index'
import { Route as AuthenticatedProfilesProfileIdEditRouteImport } from './routes/_authenticated/profiles/$profileId/edit'
import { Route as AuthenticatedInvoiceTemplatesTemplateIdEditRouteImport } from './routes/_authenticated/invoice-templates/$templateId/edit'
import { Route as AuthenticatedCountriesCountryIdEditRouteImport } from './routes/_authenticated/countries/$countryId/edit'
import { Route as AuthenticatedCheckoutShippingMethodsNewRouteImport } from './routes/_authenticated/checkout/shipping-methods/new'
import { Route as AuthenticatedCheckoutOrderNotesNewRouteImport } from './routes/_authenticated/checkout/order-notes/new'
import { Route as AuthenticatedCheckoutCouriersNewRouteImport } from './routes/_authenticated/checkout/couriers/new'
import { Route as AuthenticatedCheckoutCouponsNewRouteImport } from './routes/_authenticated/checkout/coupons/new'
import { Route as AuthenticatedCatalogTagsNewRouteImport } from './routes/_authenticated/catalog/tags/new'
import { Route as AuthenticatedCatalogSuppliersNewRouteImport } from './routes/_authenticated/catalog/suppliers/new'
import { Route as AuthenticatedCatalogProductsNewRouteImport } from './routes/_authenticated/catalog/products/new'
import { Route as AuthenticatedCatalogManufacturersNewRouteImport } from './routes/_authenticated/catalog/manufacturers/new'
import { Route as AuthenticatedCatalogDeliveriesNewRouteImport } from './routes/_authenticated/catalog/deliveries/new'
import { Route as AuthenticatedCatalogCategoriesNewRouteImport } from './routes/_authenticated/catalog/categories/new'
import { Route as AuthenticatedAddressesAddressIdEditRouteImport } from './routes/_authenticated/addresses/$addressId/edit'
import { Route as AuthenticatedCheckoutShippingMethodsMethodIdEditRouteImport } from './routes/_authenticated/checkout/shipping-methods/$methodId/edit'
import { Route as AuthenticatedCheckoutShipmentsShipmentIdEditRouteImport } from './routes/_authenticated/checkout/shipments/$shipmentId/edit'
import { Route as AuthenticatedCheckoutOrderNotesNoteIdEditRouteImport } from './routes/_authenticated/checkout/order-notes/$noteId/edit'
import { Route as AuthenticatedCheckoutCouriersCourierIdEditRouteImport } from './routes/_authenticated/checkout/couriers/$courierId/edit'
import { Route as AuthenticatedCheckoutCouponsCouponIdEditRouteImport } from './routes/_authenticated/checkout/coupons/$couponId/edit'
import { Route as AuthenticatedCatalogTagsTagIdEditRouteImport } from './routes/_authenticated/catalog/tags/$tagId/edit'
import { Route as AuthenticatedCatalogSuppliersSupplierIdEditRouteImport } from './routes/_authenticated/catalog/suppliers/$supplierId/edit'
import { Route as AuthenticatedCatalogProductsProductIdEditRouteImport } from './routes/_authenticated/catalog/products/$productId/edit'
import { Route as AuthenticatedCatalogManufacturersManufacturerIdEditRouteImport } from './routes/_authenticated/catalog/manufacturers/$manufacturerId/edit'
import { Route as AuthenticatedCatalogDeliveriesDeliveryIdEditRouteImport } from './routes/_authenticated/catalog/deliveries/$deliveryId/edit'
import { Route as AuthenticatedCatalogCategoriesCategoryIdEditRouteImport } from './routes/_authenticated/catalog/categories/$categoryId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilesIndexRoute =
  AuthenticatedProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTemplatesIndexRoute =
  AuthenticatedInvoiceTemplatesIndexRouteImport.update({
    id: '/invoice-templates/',
    path: '/invoice-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesIndexRoute =
  AuthenticatedCountriesIndexRouteImport.update({
    id: '/countries/',
    path: '/countries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressesIndexRoute =
  AuthenticatedAddressesIndexRouteImport.update({
    id: '/addresses/',
    path: '/addresses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTemplatesNewRoute =
  AuthenticatedInvoiceTemplatesNewRouteImport.update({
    id: '/invoice-templates/new',
    path: '/invoice-templates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesNewRoute =
  AuthenticatedCountriesNewRouteImport.update({
    id: '/countries/new',
    path: '/countries/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressesNewRoute =
  AuthenticatedAddressesNewRouteImport.update({
    id: '/addresses/new',
    path: '/addresses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdIndexRoute =
  AuthenticatedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsPreferencesIndexRoute =
  AuthenticatedNotificationsPreferencesIndexRouteImport.update({
    id: '/notifications/preferences/',
    path: '/notifications/preferences/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsHistoryIndexRoute =
  AuthenticatedNotificationsHistoryIndexRouteImport.update({
    id: '/notifications/history/',
    path: '/notifications/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutShippingMethodsIndexRoute =
  AuthenticatedCheckoutShippingMethodsIndexRouteImport.update({
    id: '/checkout/shipping-methods/',
    path: '/checkout/shipping-methods/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutShipmentsIndexRoute =
  AuthenticatedCheckoutShipmentsIndexRouteImport.update({
    id: '/checkout/shipments/',
    path: '/checkout/shipments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutPaymentsIndexRoute =
  AuthenticatedCheckoutPaymentsIndexRouteImport.update({
    id: '/checkout/payments/',
    path: '/checkout/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutOrderNotesIndexRoute =
  AuthenticatedCheckoutOrderNotesIndexRouteImport.update({
    id: '/checkout/order-notes/',
    path: '/checkout/order-notes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutInvoicesIndexRoute =
  AuthenticatedCheckoutInvoicesIndexRouteImport.update({
    id: '/checkout/invoices/',
    path: '/checkout/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouriersIndexRoute =
  AuthenticatedCheckoutCouriersIndexRouteImport.update({
    id: '/checkout/couriers/',
    path: '/checkout/couriers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouponsIndexRoute =
  AuthenticatedCheckoutCouponsIndexRouteImport.update({
    id: '/checkout/coupons/',
    path: '/checkout/coupons/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouponRedemptionsIndexRoute =
  AuthenticatedCheckoutCouponRedemptionsIndexRouteImport.update({
    id: '/checkout/coupon-redemptions/',
    path: '/checkout/coupon-redemptions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogTagsIndexRoute =
  AuthenticatedCatalogTagsIndexRouteImport.update({
    id: '/catalog/tags/',
    path: '/catalog/tags/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogSuppliersIndexRoute =
  AuthenticatedCatalogSuppliersIndexRouteImport.update({
    id: '/catalog/suppliers/',
    path: '/catalog/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProductsIndexRoute =
  AuthenticatedCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersIndexRoute =
  AuthenticatedCatalogManufacturersIndexRouteImport.update({
    id: '/catalog/manufacturers/',
    path: '/catalog/manufacturers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogDeliveriesIndexRoute =
  AuthenticatedCatalogDeliveriesIndexRouteImport.update({
    id: '/catalog/deliveries/',
    path: '/catalog/deliveries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesIndexRoute =
  AuthenticatedCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdEditRoute =
  AuthenticatedProfilesProfileIdEditRouteImport.update({
    id: '/profiles/$profileId/edit',
    path: '/profiles/$profileId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTemplatesTemplateIdEditRoute =
  AuthenticatedInvoiceTemplatesTemplateIdEditRouteImport.update({
    id: '/invoice-templates/$templateId/edit',
    path: '/invoice-templates/$templateId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesCountryIdEditRoute =
  AuthenticatedCountriesCountryIdEditRouteImport.update({
    id: '/countries/$countryId/edit',
    path: '/countries/$countryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutShippingMethodsNewRoute =
  AuthenticatedCheckoutShippingMethodsNewRouteImport.update({
    id: '/checkout/shipping-methods/new',
    path: '/checkout/shipping-methods/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutOrderNotesNewRoute =
  AuthenticatedCheckoutOrderNotesNewRouteImport.update({
    id: '/checkout/order-notes/new',
    path: '/checkout/order-notes/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouriersNewRoute =
  AuthenticatedCheckoutCouriersNewRouteImport.update({
    id: '/checkout/couriers/new',
    path: '/checkout/couriers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouponsNewRoute =
  AuthenticatedCheckoutCouponsNewRouteImport.update({
    id: '/checkout/coupons/new',
    path: '/checkout/coupons/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogTagsNewRoute =
  AuthenticatedCatalogTagsNewRouteImport.update({
    id: '/catalog/tags/new',
    path: '/catalog/tags/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogSuppliersNewRoute =
  AuthenticatedCatalogSuppliersNewRouteImport.update({
    id: '/catalog/suppliers/new',
    path: '/catalog/suppliers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProductsNewRoute =
  AuthenticatedCatalogProductsNewRouteImport.update({
    id: '/catalog/products/new',
    path: '/catalog/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersNewRoute =
  AuthenticatedCatalogManufacturersNewRouteImport.update({
    id: '/catalog/manufacturers/new',
    path: '/catalog/manufacturers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogDeliveriesNewRoute =
  AuthenticatedCatalogDeliveriesNewRouteImport.update({
    id: '/catalog/deliveries/new',
    path: '/catalog/deliveries/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesNewRoute =
  AuthenticatedCatalogCategoriesNewRouteImport.update({
    id: '/catalog/categories/new',
    path: '/catalog/categories/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressesAddressIdEditRoute =
  AuthenticatedAddressesAddressIdEditRouteImport.update({
    id: '/addresses/$addressId/edit',
    path: '/addresses/$addressId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutShippingMethodsMethodIdEditRoute =
  AuthenticatedCheckoutShippingMethodsMethodIdEditRouteImport.update({
    id: '/checkout/shipping-methods/$methodId/edit',
    path: '/checkout/shipping-methods/$methodId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutShipmentsShipmentIdEditRoute =
  AuthenticatedCheckoutShipmentsShipmentIdEditRouteImport.update({
    id: '/checkout/shipments/$shipmentId/edit',
    path: '/checkout/shipments/$shipmentId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutOrderNotesNoteIdEditRoute =
  AuthenticatedCheckoutOrderNotesNoteIdEditRouteImport.update({
    id: '/checkout/order-notes/$noteId/edit',
    path: '/checkout/order-notes/$noteId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouriersCourierIdEditRoute =
  AuthenticatedCheckoutCouriersCourierIdEditRouteImport.update({
    id: '/checkout/couriers/$courierId/edit',
    path: '/checkout/couriers/$courierId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCouponsCouponIdEditRoute =
  AuthenticatedCheckoutCouponsCouponIdEditRouteImport.update({
    id: '/checkout/coupons/$couponId/edit',
    path: '/checkout/coupons/$couponId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogTagsTagIdEditRoute =
  AuthenticatedCatalogTagsTagIdEditRouteImport.update({
    id: '/catalog/tags/$tagId/edit',
    path: '/catalog/tags/$tagId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogSuppliersSupplierIdEditRoute =
  AuthenticatedCatalogSuppliersSupplierIdEditRouteImport.update({
    id: '/catalog/suppliers/$supplierId/edit',
    path: '/catalog/suppliers/$supplierId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProductsProductIdEditRoute =
  AuthenticatedCatalogProductsProductIdEditRouteImport.update({
    id: '/catalog/products/$productId/edit',
    path: '/catalog/products/$productId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersManufacturerIdEditRoute =
  AuthenticatedCatalogManufacturersManufacturerIdEditRouteImport.update({
    id: '/catalog/manufacturers/$manufacturerId/edit',
    path: '/catalog/manufacturers/$manufacturerId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogDeliveriesDeliveryIdEditRoute =
  AuthenticatedCatalogDeliveriesDeliveryIdEditRouteImport.update({
    id: '/catalog/deliveries/$deliveryId/edit',
    path: '/catalog/deliveries/$deliveryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesCategoryIdEditRoute =
  AuthenticatedCatalogCategoriesCategoryIdEditRouteImport.update({
    id: '/catalog/categories/$categoryId/edit',
    path: '/catalog/categories/$categoryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/addresses/new': typeof AuthenticatedAddressesNewRoute
  '/countries/new': typeof AuthenticatedCountriesNewRoute
  '/invoice-templates/new': typeof AuthenticatedInvoiceTemplatesNewRoute
  '/addresses': typeof AuthenticatedAddressesIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/invoice-templates': typeof AuthenticatedInvoiceTemplatesIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/addresses/$addressId/edit': typeof AuthenticatedAddressesAddressIdEditRoute
  '/catalog/categories/new': typeof AuthenticatedCatalogCategoriesNewRoute
  '/catalog/deliveries/new': typeof AuthenticatedCatalogDeliveriesNewRoute
  '/catalog/manufacturers/new': typeof AuthenticatedCatalogManufacturersNewRoute
  '/catalog/products/new': typeof AuthenticatedCatalogProductsNewRoute
  '/catalog/suppliers/new': typeof AuthenticatedCatalogSuppliersNewRoute
  '/catalog/tags/new': typeof AuthenticatedCatalogTagsNewRoute
  '/checkout/coupons/new': typeof AuthenticatedCheckoutCouponsNewRoute
  '/checkout/couriers/new': typeof AuthenticatedCheckoutCouriersNewRoute
  '/checkout/order-notes/new': typeof AuthenticatedCheckoutOrderNotesNewRoute
  '/checkout/shipping-methods/new': typeof AuthenticatedCheckoutShippingMethodsNewRoute
  '/countries/$countryId/edit': typeof AuthenticatedCountriesCountryIdEditRoute
  '/invoice-templates/$templateId/edit': typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  '/profiles/$profileId/edit': typeof AuthenticatedProfilesProfileIdEditRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/catalog/deliveries': typeof AuthenticatedCatalogDeliveriesIndexRoute
  '/catalog/manufacturers': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/suppliers': typeof AuthenticatedCatalogSuppliersIndexRoute
  '/catalog/tags': typeof AuthenticatedCatalogTagsIndexRoute
  '/checkout/coupon-redemptions': typeof AuthenticatedCheckoutCouponRedemptionsIndexRoute
  '/checkout/coupons': typeof AuthenticatedCheckoutCouponsIndexRoute
  '/checkout/couriers': typeof AuthenticatedCheckoutCouriersIndexRoute
  '/checkout/invoices': typeof AuthenticatedCheckoutInvoicesIndexRoute
  '/checkout/order-notes': typeof AuthenticatedCheckoutOrderNotesIndexRoute
  '/checkout/payments': typeof AuthenticatedCheckoutPaymentsIndexRoute
  '/checkout/shipments': typeof AuthenticatedCheckoutShipmentsIndexRoute
  '/checkout/shipping-methods': typeof AuthenticatedCheckoutShippingMethodsIndexRoute
  '/notifications/history': typeof AuthenticatedNotificationsHistoryIndexRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdIndexRoute
  '/catalog/categories/$categoryId/edit': typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  '/catalog/deliveries/$deliveryId/edit': typeof AuthenticatedCatalogDeliveriesDeliveryIdEditRoute
  '/catalog/manufacturers/$manufacturerId/edit': typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  '/catalog/products/$productId/edit': typeof AuthenticatedCatalogProductsProductIdEditRoute
  '/catalog/suppliers/$supplierId/edit': typeof AuthenticatedCatalogSuppliersSupplierIdEditRoute
  '/catalog/tags/$tagId/edit': typeof AuthenticatedCatalogTagsTagIdEditRoute
  '/checkout/coupons/$couponId/edit': typeof AuthenticatedCheckoutCouponsCouponIdEditRoute
  '/checkout/couriers/$courierId/edit': typeof AuthenticatedCheckoutCouriersCourierIdEditRoute
  '/checkout/order-notes/$noteId/edit': typeof AuthenticatedCheckoutOrderNotesNoteIdEditRoute
  '/checkout/shipments/$shipmentId/edit': typeof AuthenticatedCheckoutShipmentsShipmentIdEditRoute
  '/checkout/shipping-methods/$methodId/edit': typeof AuthenticatedCheckoutShippingMethodsMethodIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/addresses/new': typeof AuthenticatedAddressesNewRoute
  '/countries/new': typeof AuthenticatedCountriesNewRoute
  '/invoice-templates/new': typeof AuthenticatedInvoiceTemplatesNewRoute
  '/addresses': typeof AuthenticatedAddressesIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/invoice-templates': typeof AuthenticatedInvoiceTemplatesIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/addresses/$addressId/edit': typeof AuthenticatedAddressesAddressIdEditRoute
  '/catalog/categories/new': typeof AuthenticatedCatalogCategoriesNewRoute
  '/catalog/deliveries/new': typeof AuthenticatedCatalogDeliveriesNewRoute
  '/catalog/manufacturers/new': typeof AuthenticatedCatalogManufacturersNewRoute
  '/catalog/products/new': typeof AuthenticatedCatalogProductsNewRoute
  '/catalog/suppliers/new': typeof AuthenticatedCatalogSuppliersNewRoute
  '/catalog/tags/new': typeof AuthenticatedCatalogTagsNewRoute
  '/checkout/coupons/new': typeof AuthenticatedCheckoutCouponsNewRoute
  '/checkout/couriers/new': typeof AuthenticatedCheckoutCouriersNewRoute
  '/checkout/order-notes/new': typeof AuthenticatedCheckoutOrderNotesNewRoute
  '/checkout/shipping-methods/new': typeof AuthenticatedCheckoutShippingMethodsNewRoute
  '/countries/$countryId/edit': typeof AuthenticatedCountriesCountryIdEditRoute
  '/invoice-templates/$templateId/edit': typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  '/profiles/$profileId/edit': typeof AuthenticatedProfilesProfileIdEditRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/catalog/deliveries': typeof AuthenticatedCatalogDeliveriesIndexRoute
  '/catalog/manufacturers': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/suppliers': typeof AuthenticatedCatalogSuppliersIndexRoute
  '/catalog/tags': typeof AuthenticatedCatalogTagsIndexRoute
  '/checkout/coupon-redemptions': typeof AuthenticatedCheckoutCouponRedemptionsIndexRoute
  '/checkout/coupons': typeof AuthenticatedCheckoutCouponsIndexRoute
  '/checkout/couriers': typeof AuthenticatedCheckoutCouriersIndexRoute
  '/checkout/invoices': typeof AuthenticatedCheckoutInvoicesIndexRoute
  '/checkout/order-notes': typeof AuthenticatedCheckoutOrderNotesIndexRoute
  '/checkout/payments': typeof AuthenticatedCheckoutPaymentsIndexRoute
  '/checkout/shipments': typeof AuthenticatedCheckoutShipmentsIndexRoute
  '/checkout/shipping-methods': typeof AuthenticatedCheckoutShippingMethodsIndexRoute
  '/notifications/history': typeof AuthenticatedNotificationsHistoryIndexRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdIndexRoute
  '/catalog/categories/$categoryId/edit': typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  '/catalog/deliveries/$deliveryId/edit': typeof AuthenticatedCatalogDeliveriesDeliveryIdEditRoute
  '/catalog/manufacturers/$manufacturerId/edit': typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  '/catalog/products/$productId/edit': typeof AuthenticatedCatalogProductsProductIdEditRoute
  '/catalog/suppliers/$supplierId/edit': typeof AuthenticatedCatalogSuppliersSupplierIdEditRoute
  '/catalog/tags/$tagId/edit': typeof AuthenticatedCatalogTagsTagIdEditRoute
  '/checkout/coupons/$couponId/edit': typeof AuthenticatedCheckoutCouponsCouponIdEditRoute
  '/checkout/couriers/$courierId/edit': typeof AuthenticatedCheckoutCouriersCourierIdEditRoute
  '/checkout/order-notes/$noteId/edit': typeof AuthenticatedCheckoutOrderNotesNoteIdEditRoute
  '/checkout/shipments/$shipmentId/edit': typeof AuthenticatedCheckoutShipmentsShipmentIdEditRoute
  '/checkout/shipping-methods/$methodId/edit': typeof AuthenticatedCheckoutShippingMethodsMethodIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/addresses/new': typeof AuthenticatedAddressesNewRoute
  '/_authenticated/countries/new': typeof AuthenticatedCountriesNewRoute
  '/_authenticated/invoice-templates/new': typeof AuthenticatedInvoiceTemplatesNewRoute
  '/_authenticated/addresses/': typeof AuthenticatedAddressesIndexRoute
  '/_authenticated/countries/': typeof AuthenticatedCountriesIndexRoute
  '/_authenticated/invoice-templates/': typeof AuthenticatedInvoiceTemplatesIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/_authenticated/addresses/$addressId/edit': typeof AuthenticatedAddressesAddressIdEditRoute
  '/_authenticated/catalog/categories/new': typeof AuthenticatedCatalogCategoriesNewRoute
  '/_authenticated/catalog/deliveries/new': typeof AuthenticatedCatalogDeliveriesNewRoute
  '/_authenticated/catalog/manufacturers/new': typeof AuthenticatedCatalogManufacturersNewRoute
  '/_authenticated/catalog/products/new': typeof AuthenticatedCatalogProductsNewRoute
  '/_authenticated/catalog/suppliers/new': typeof AuthenticatedCatalogSuppliersNewRoute
  '/_authenticated/catalog/tags/new': typeof AuthenticatedCatalogTagsNewRoute
  '/_authenticated/checkout/coupons/new': typeof AuthenticatedCheckoutCouponsNewRoute
  '/_authenticated/checkout/couriers/new': typeof AuthenticatedCheckoutCouriersNewRoute
  '/_authenticated/checkout/order-notes/new': typeof AuthenticatedCheckoutOrderNotesNewRoute
  '/_authenticated/checkout/shipping-methods/new': typeof AuthenticatedCheckoutShippingMethodsNewRoute
  '/_authenticated/countries/$countryId/edit': typeof AuthenticatedCountriesCountryIdEditRoute
  '/_authenticated/invoice-templates/$templateId/edit': typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  '/_authenticated/profiles/$profileId/edit': typeof AuthenticatedProfilesProfileIdEditRoute
  '/_authenticated/catalog/categories/': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/_authenticated/catalog/deliveries/': typeof AuthenticatedCatalogDeliveriesIndexRoute
  '/_authenticated/catalog/manufacturers/': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/_authenticated/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/_authenticated/catalog/suppliers/': typeof AuthenticatedCatalogSuppliersIndexRoute
  '/_authenticated/catalog/tags/': typeof AuthenticatedCatalogTagsIndexRoute
  '/_authenticated/checkout/coupon-redemptions/': typeof AuthenticatedCheckoutCouponRedemptionsIndexRoute
  '/_authenticated/checkout/coupons/': typeof AuthenticatedCheckoutCouponsIndexRoute
  '/_authenticated/checkout/couriers/': typeof AuthenticatedCheckoutCouriersIndexRoute
  '/_authenticated/checkout/invoices/': typeof AuthenticatedCheckoutInvoicesIndexRoute
  '/_authenticated/checkout/order-notes/': typeof AuthenticatedCheckoutOrderNotesIndexRoute
  '/_authenticated/checkout/payments/': typeof AuthenticatedCheckoutPaymentsIndexRoute
  '/_authenticated/checkout/shipments/': typeof AuthenticatedCheckoutShipmentsIndexRoute
  '/_authenticated/checkout/shipping-methods/': typeof AuthenticatedCheckoutShippingMethodsIndexRoute
  '/_authenticated/notifications/history/': typeof AuthenticatedNotificationsHistoryIndexRoute
  '/_authenticated/notifications/preferences/': typeof AuthenticatedNotificationsPreferencesIndexRoute
  '/_authenticated/orders/$orderId/': typeof AuthenticatedOrdersOrderIdIndexRoute
  '/_authenticated/catalog/categories/$categoryId/edit': typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  '/_authenticated/catalog/deliveries/$deliveryId/edit': typeof AuthenticatedCatalogDeliveriesDeliveryIdEditRoute
  '/_authenticated/catalog/manufacturers/$manufacturerId/edit': typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  '/_authenticated/catalog/products/$productId/edit': typeof AuthenticatedCatalogProductsProductIdEditRoute
  '/_authenticated/catalog/suppliers/$supplierId/edit': typeof AuthenticatedCatalogSuppliersSupplierIdEditRoute
  '/_authenticated/catalog/tags/$tagId/edit': typeof AuthenticatedCatalogTagsTagIdEditRoute
  '/_authenticated/checkout/coupons/$couponId/edit': typeof AuthenticatedCheckoutCouponsCouponIdEditRoute
  '/_authenticated/checkout/couriers/$courierId/edit': typeof AuthenticatedCheckoutCouriersCourierIdEditRoute
  '/_authenticated/checkout/order-notes/$noteId/edit': typeof AuthenticatedCheckoutOrderNotesNoteIdEditRoute
  '/_authenticated/checkout/shipments/$shipmentId/edit': typeof AuthenticatedCheckoutShipmentsShipmentIdEditRoute
  '/_authenticated/checkout/shipping-methods/$methodId/edit': typeof AuthenticatedCheckoutShippingMethodsMethodIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/addresses/new'
    | '/countries/new'
    | '/invoice-templates/new'
    | '/addresses'
    | '/countries'
    | '/invoice-templates'
    | '/orders'
    | '/profiles'
    | '/addresses/$addressId/edit'
    | '/catalog/categories/new'
    | '/catalog/deliveries/new'
    | '/catalog/manufacturers/new'
    | '/catalog/products/new'
    | '/catalog/suppliers/new'
    | '/catalog/tags/new'
    | '/checkout/coupons/new'
    | '/checkout/couriers/new'
    | '/checkout/order-notes/new'
    | '/checkout/shipping-methods/new'
    | '/countries/$countryId/edit'
    | '/invoice-templates/$templateId/edit'
    | '/profiles/$profileId/edit'
    | '/catalog/categories'
    | '/catalog/deliveries'
    | '/catalog/manufacturers'
    | '/catalog/products'
    | '/catalog/suppliers'
    | '/catalog/tags'
    | '/checkout/coupon-redemptions'
    | '/checkout/coupons'
    | '/checkout/couriers'
    | '/checkout/invoices'
    | '/checkout/order-notes'
    | '/checkout/payments'
    | '/checkout/shipments'
    | '/checkout/shipping-methods'
    | '/notifications/history'
    | '/notifications/preferences'
    | '/orders/$orderId'
    | '/catalog/categories/$categoryId/edit'
    | '/catalog/deliveries/$deliveryId/edit'
    | '/catalog/manufacturers/$manufacturerId/edit'
    | '/catalog/products/$productId/edit'
    | '/catalog/suppliers/$supplierId/edit'
    | '/catalog/tags/$tagId/edit'
    | '/checkout/coupons/$couponId/edit'
    | '/checkout/couriers/$courierId/edit'
    | '/checkout/order-notes/$noteId/edit'
    | '/checkout/shipments/$shipmentId/edit'
    | '/checkout/shipping-methods/$methodId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/addresses/new'
    | '/countries/new'
    | '/invoice-templates/new'
    | '/addresses'
    | '/countries'
    | '/invoice-templates'
    | '/orders'
    | '/profiles'
    | '/addresses/$addressId/edit'
    | '/catalog/categories/new'
    | '/catalog/deliveries/new'
    | '/catalog/manufacturers/new'
    | '/catalog/products/new'
    | '/catalog/suppliers/new'
    | '/catalog/tags/new'
    | '/checkout/coupons/new'
    | '/checkout/couriers/new'
    | '/checkout/order-notes/new'
    | '/checkout/shipping-methods/new'
    | '/countries/$countryId/edit'
    | '/invoice-templates/$templateId/edit'
    | '/profiles/$profileId/edit'
    | '/catalog/categories'
    | '/catalog/deliveries'
    | '/catalog/manufacturers'
    | '/catalog/products'
    | '/catalog/suppliers'
    | '/catalog/tags'
    | '/checkout/coupon-redemptions'
    | '/checkout/coupons'
    | '/checkout/couriers'
    | '/checkout/invoices'
    | '/checkout/order-notes'
    | '/checkout/payments'
    | '/checkout/shipments'
    | '/checkout/shipping-methods'
    | '/notifications/history'
    | '/notifications/preferences'
    | '/orders/$orderId'
    | '/catalog/categories/$categoryId/edit'
    | '/catalog/deliveries/$deliveryId/edit'
    | '/catalog/manufacturers/$manufacturerId/edit'
    | '/catalog/products/$productId/edit'
    | '/catalog/suppliers/$supplierId/edit'
    | '/catalog/tags/$tagId/edit'
    | '/checkout/coupons/$couponId/edit'
    | '/checkout/couriers/$courierId/edit'
    | '/checkout/order-notes/$noteId/edit'
    | '/checkout/shipments/$shipmentId/edit'
    | '/checkout/shipping-methods/$methodId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/addresses/new'
    | '/_authenticated/countries/new'
    | '/_authenticated/invoice-templates/new'
    | '/_authenticated/addresses/'
    | '/_authenticated/countries/'
    | '/_authenticated/invoice-templates/'
    | '/_authenticated/orders/'
    | '/_authenticated/profiles/'
    | '/_authenticated/addresses/$addressId/edit'
    | '/_authenticated/catalog/categories/new'
    | '/_authenticated/catalog/deliveries/new'
    | '/_authenticated/catalog/manufacturers/new'
    | '/_authenticated/catalog/products/new'
    | '/_authenticated/catalog/suppliers/new'
    | '/_authenticated/catalog/tags/new'
    | '/_authenticated/checkout/coupons/new'
    | '/_authenticated/checkout/couriers/new'
    | '/_authenticated/checkout/order-notes/new'
    | '/_authenticated/checkout/shipping-methods/new'
    | '/_authenticated/countries/$countryId/edit'
    | '/_authenticated/invoice-templates/$templateId/edit'
    | '/_authenticated/profiles/$profileId/edit'
    | '/_authenticated/catalog/categories/'
    | '/_authenticated/catalog/deliveries/'
    | '/_authenticated/catalog/manufacturers/'
    | '/_authenticated/catalog/products/'
    | '/_authenticated/catalog/suppliers/'
    | '/_authenticated/catalog/tags/'
    | '/_authenticated/checkout/coupon-redemptions/'
    | '/_authenticated/checkout/coupons/'
    | '/_authenticated/checkout/couriers/'
    | '/_authenticated/checkout/invoices/'
    | '/_authenticated/checkout/order-notes/'
    | '/_authenticated/checkout/payments/'
    | '/_authenticated/checkout/shipments/'
    | '/_authenticated/checkout/shipping-methods/'
    | '/_authenticated/notifications/history/'
    | '/_authenticated/notifications/preferences/'
    | '/_authenticated/orders/$orderId/'
    | '/_authenticated/catalog/categories/$categoryId/edit'
    | '/_authenticated/catalog/deliveries/$deliveryId/edit'
    | '/_authenticated/catalog/manufacturers/$manufacturerId/edit'
    | '/_authenticated/catalog/products/$productId/edit'
    | '/_authenticated/catalog/suppliers/$supplierId/edit'
    | '/_authenticated/catalog/tags/$tagId/edit'
    | '/_authenticated/checkout/coupons/$couponId/edit'
    | '/_authenticated/checkout/couriers/$courierId/edit'
    | '/_authenticated/checkout/order-notes/$noteId/edit'
    | '/_authenticated/checkout/shipments/$shipmentId/edit'
    | '/_authenticated/checkout/shipping-methods/$methodId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/': {
      id: '/_authenticated/profiles/'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice-templates/': {
      id: '/_authenticated/invoice-templates/'
      path: '/invoice-templates'
      fullPath: '/invoice-templates'
      preLoaderRoute: typeof AuthenticatedInvoiceTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/': {
      id: '/_authenticated/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedCountriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addresses/': {
      id: '/_authenticated/addresses/'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice-templates/new': {
      id: '/_authenticated/invoice-templates/new'
      path: '/invoice-templates/new'
      fullPath: '/invoice-templates/new'
      preLoaderRoute: typeof AuthenticatedInvoiceTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/new': {
      id: '/_authenticated/countries/new'
      path: '/countries/new'
      fullPath: '/countries/new'
      preLoaderRoute: typeof AuthenticatedCountriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addresses/new': {
      id: '/_authenticated/addresses/new'
      path: '/addresses/new'
      fullPath: '/addresses/new'
      preLoaderRoute: typeof AuthenticatedAddressesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId/': {
      id: '/_authenticated/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/preferences/': {
      id: '/_authenticated/notifications/preferences/'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof AuthenticatedNotificationsPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/history/': {
      id: '/_authenticated/notifications/history/'
      path: '/notifications/history'
      fullPath: '/notifications/history'
      preLoaderRoute: typeof AuthenticatedNotificationsHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/shipping-methods/': {
      id: '/_authenticated/checkout/shipping-methods/'
      path: '/checkout/shipping-methods'
      fullPath: '/checkout/shipping-methods'
      preLoaderRoute: typeof AuthenticatedCheckoutShippingMethodsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/shipments/': {
      id: '/_authenticated/checkout/shipments/'
      path: '/checkout/shipments'
      fullPath: '/checkout/shipments'
      preLoaderRoute: typeof AuthenticatedCheckoutShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/payments/': {
      id: '/_authenticated/checkout/payments/'
      path: '/checkout/payments'
      fullPath: '/checkout/payments'
      preLoaderRoute: typeof AuthenticatedCheckoutPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/order-notes/': {
      id: '/_authenticated/checkout/order-notes/'
      path: '/checkout/order-notes'
      fullPath: '/checkout/order-notes'
      preLoaderRoute: typeof AuthenticatedCheckoutOrderNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/invoices/': {
      id: '/_authenticated/checkout/invoices/'
      path: '/checkout/invoices'
      fullPath: '/checkout/invoices'
      preLoaderRoute: typeof AuthenticatedCheckoutInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/couriers/': {
      id: '/_authenticated/checkout/couriers/'
      path: '/checkout/couriers'
      fullPath: '/checkout/couriers'
      preLoaderRoute: typeof AuthenticatedCheckoutCouriersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/coupons/': {
      id: '/_authenticated/checkout/coupons/'
      path: '/checkout/coupons'
      fullPath: '/checkout/coupons'
      preLoaderRoute: typeof AuthenticatedCheckoutCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/coupon-redemptions/': {
      id: '/_authenticated/checkout/coupon-redemptions/'
      path: '/checkout/coupon-redemptions'
      fullPath: '/checkout/coupon-redemptions'
      preLoaderRoute: typeof AuthenticatedCheckoutCouponRedemptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/tags/': {
      id: '/_authenticated/catalog/tags/'
      path: '/catalog/tags'
      fullPath: '/catalog/tags'
      preLoaderRoute: typeof AuthenticatedCatalogTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/suppliers/': {
      id: '/_authenticated/catalog/suppliers/'
      path: '/catalog/suppliers'
      fullPath: '/catalog/suppliers'
      preLoaderRoute: typeof AuthenticatedCatalogSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/products/': {
      id: '/_authenticated/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof AuthenticatedCatalogProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/': {
      id: '/_authenticated/catalog/manufacturers/'
      path: '/catalog/manufacturers'
      fullPath: '/catalog/manufacturers'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/deliveries/': {
      id: '/_authenticated/catalog/deliveries/'
      path: '/catalog/deliveries'
      fullPath: '/catalog/deliveries'
      preLoaderRoute: typeof AuthenticatedCatalogDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories/': {
      id: '/_authenticated/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/edit': {
      id: '/_authenticated/profiles/$profileId/edit'
      path: '/profiles/$profileId/edit'
      fullPath: '/profiles/$profileId/edit'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice-templates/$templateId/edit': {
      id: '/_authenticated/invoice-templates/$templateId/edit'
      path: '/invoice-templates/$templateId/edit'
      fullPath: '/invoice-templates/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedInvoiceTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/$countryId/edit': {
      id: '/_authenticated/countries/$countryId/edit'
      path: '/countries/$countryId/edit'
      fullPath: '/countries/$countryId/edit'
      preLoaderRoute: typeof AuthenticatedCountriesCountryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/shipping-methods/new': {
      id: '/_authenticated/checkout/shipping-methods/new'
      path: '/checkout/shipping-methods/new'
      fullPath: '/checkout/shipping-methods/new'
      preLoaderRoute: typeof AuthenticatedCheckoutShippingMethodsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/order-notes/new': {
      id: '/_authenticated/checkout/order-notes/new'
      path: '/checkout/order-notes/new'
      fullPath: '/checkout/order-notes/new'
      preLoaderRoute: typeof AuthenticatedCheckoutOrderNotesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/couriers/new': {
      id: '/_authenticated/checkout/couriers/new'
      path: '/checkout/couriers/new'
      fullPath: '/checkout/couriers/new'
      preLoaderRoute: typeof AuthenticatedCheckoutCouriersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/coupons/new': {
      id: '/_authenticated/checkout/coupons/new'
      path: '/checkout/coupons/new'
      fullPath: '/checkout/coupons/new'
      preLoaderRoute: typeof AuthenticatedCheckoutCouponsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/tags/new': {
      id: '/_authenticated/catalog/tags/new'
      path: '/catalog/tags/new'
      fullPath: '/catalog/tags/new'
      preLoaderRoute: typeof AuthenticatedCatalogTagsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/suppliers/new': {
      id: '/_authenticated/catalog/suppliers/new'
      path: '/catalog/suppliers/new'
      fullPath: '/catalog/suppliers/new'
      preLoaderRoute: typeof AuthenticatedCatalogSuppliersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/products/new': {
      id: '/_authenticated/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/catalog/products/new'
      preLoaderRoute: typeof AuthenticatedCatalogProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/new': {
      id: '/_authenticated/catalog/manufacturers/new'
      path: '/catalog/manufacturers/new'
      fullPath: '/catalog/manufacturers/new'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/deliveries/new': {
      id: '/_authenticated/catalog/deliveries/new'
      path: '/catalog/deliveries/new'
      fullPath: '/catalog/deliveries/new'
      preLoaderRoute: typeof AuthenticatedCatalogDeliveriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories/new': {
      id: '/_authenticated/catalog/categories/new'
      path: '/catalog/categories/new'
      fullPath: '/catalog/categories/new'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addresses/$addressId/edit': {
      id: '/_authenticated/addresses/$addressId/edit'
      path: '/addresses/$addressId/edit'
      fullPath: '/addresses/$addressId/edit'
      preLoaderRoute: typeof AuthenticatedAddressesAddressIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/shipping-methods/$methodId/edit': {
      id: '/_authenticated/checkout/shipping-methods/$methodId/edit'
      path: '/checkout/shipping-methods/$methodId/edit'
      fullPath: '/checkout/shipping-methods/$methodId/edit'
      preLoaderRoute: typeof AuthenticatedCheckoutShippingMethodsMethodIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/shipments/$shipmentId/edit': {
      id: '/_authenticated/checkout/shipments/$shipmentId/edit'
      path: '/checkout/shipments/$shipmentId/edit'
      fullPath: '/checkout/shipments/$shipmentId/edit'
      preLoaderRoute: typeof AuthenticatedCheckoutShipmentsShipmentIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/order-notes/$noteId/edit': {
      id: '/_authenticated/checkout/order-notes/$noteId/edit'
      path: '/checkout/order-notes/$noteId/edit'
      fullPath: '/checkout/order-notes/$noteId/edit'
      preLoaderRoute: typeof AuthenticatedCheckoutOrderNotesNoteIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/couriers/$courierId/edit': {
      id: '/_authenticated/checkout/couriers/$courierId/edit'
      path: '/checkout/couriers/$courierId/edit'
      fullPath: '/checkout/couriers/$courierId/edit'
      preLoaderRoute: typeof AuthenticatedCheckoutCouriersCourierIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/coupons/$couponId/edit': {
      id: '/_authenticated/checkout/coupons/$couponId/edit'
      path: '/checkout/coupons/$couponId/edit'
      fullPath: '/checkout/coupons/$couponId/edit'
      preLoaderRoute: typeof AuthenticatedCheckoutCouponsCouponIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/tags/$tagId/edit': {
      id: '/_authenticated/catalog/tags/$tagId/edit'
      path: '/catalog/tags/$tagId/edit'
      fullPath: '/catalog/tags/$tagId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogTagsTagIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/suppliers/$supplierId/edit': {
      id: '/_authenticated/catalog/suppliers/$supplierId/edit'
      path: '/catalog/suppliers/$supplierId/edit'
      fullPath: '/catalog/suppliers/$supplierId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogSuppliersSupplierIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/products/$productId/edit': {
      id: '/_authenticated/catalog/products/$productId/edit'
      path: '/catalog/products/$productId/edit'
      fullPath: '/catalog/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/$manufacturerId/edit': {
      id: '/_authenticated/catalog/manufacturers/$manufacturerId/edit'
      path: '/catalog/manufacturers/$manufacturerId/edit'
      fullPath: '/catalog/manufacturers/$manufacturerId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersManufacturerIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/deliveries/$deliveryId/edit': {
      id: '/_authenticated/catalog/deliveries/$deliveryId/edit'
      path: '/catalog/deliveries/$deliveryId/edit'
      fullPath: '/catalog/deliveries/$deliveryId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogDeliveriesDeliveryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories/$categoryId/edit': {
      id: '/_authenticated/catalog/categories/$categoryId/edit'
      path: '/catalog/categories/$categoryId/edit'
      fullPath: '/catalog/categories/$categoryId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAddressesNewRoute: typeof AuthenticatedAddressesNewRoute
  AuthenticatedCountriesNewRoute: typeof AuthenticatedCountriesNewRoute
  AuthenticatedInvoiceTemplatesNewRoute: typeof AuthenticatedInvoiceTemplatesNewRoute
  AuthenticatedAddressesIndexRoute: typeof AuthenticatedAddressesIndexRoute
  AuthenticatedCountriesIndexRoute: typeof AuthenticatedCountriesIndexRoute
  AuthenticatedInvoiceTemplatesIndexRoute: typeof AuthenticatedInvoiceTemplatesIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProfilesIndexRoute: typeof AuthenticatedProfilesIndexRoute
  AuthenticatedAddressesAddressIdEditRoute: typeof AuthenticatedAddressesAddressIdEditRoute
  AuthenticatedCatalogCategoriesNewRoute: typeof AuthenticatedCatalogCategoriesNewRoute
  AuthenticatedCatalogDeliveriesNewRoute: typeof AuthenticatedCatalogDeliveriesNewRoute
  AuthenticatedCatalogManufacturersNewRoute: typeof AuthenticatedCatalogManufacturersNewRoute
  AuthenticatedCatalogProductsNewRoute: typeof AuthenticatedCatalogProductsNewRoute
  AuthenticatedCatalogSuppliersNewRoute: typeof AuthenticatedCatalogSuppliersNewRoute
  AuthenticatedCatalogTagsNewRoute: typeof AuthenticatedCatalogTagsNewRoute
  AuthenticatedCheckoutCouponsNewRoute: typeof AuthenticatedCheckoutCouponsNewRoute
  AuthenticatedCheckoutCouriersNewRoute: typeof AuthenticatedCheckoutCouriersNewRoute
  AuthenticatedCheckoutOrderNotesNewRoute: typeof AuthenticatedCheckoutOrderNotesNewRoute
  AuthenticatedCheckoutShippingMethodsNewRoute: typeof AuthenticatedCheckoutShippingMethodsNewRoute
  AuthenticatedCountriesCountryIdEditRoute: typeof AuthenticatedCountriesCountryIdEditRoute
  AuthenticatedInvoiceTemplatesTemplateIdEditRoute: typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  AuthenticatedProfilesProfileIdEditRoute: typeof AuthenticatedProfilesProfileIdEditRoute
  AuthenticatedCatalogCategoriesIndexRoute: typeof AuthenticatedCatalogCategoriesIndexRoute
  AuthenticatedCatalogDeliveriesIndexRoute: typeof AuthenticatedCatalogDeliveriesIndexRoute
  AuthenticatedCatalogManufacturersIndexRoute: typeof AuthenticatedCatalogManufacturersIndexRoute
  AuthenticatedCatalogProductsIndexRoute: typeof AuthenticatedCatalogProductsIndexRoute
  AuthenticatedCatalogSuppliersIndexRoute: typeof AuthenticatedCatalogSuppliersIndexRoute
  AuthenticatedCatalogTagsIndexRoute: typeof AuthenticatedCatalogTagsIndexRoute
  AuthenticatedCheckoutCouponRedemptionsIndexRoute: typeof AuthenticatedCheckoutCouponRedemptionsIndexRoute
  AuthenticatedCheckoutCouponsIndexRoute: typeof AuthenticatedCheckoutCouponsIndexRoute
  AuthenticatedCheckoutCouriersIndexRoute: typeof AuthenticatedCheckoutCouriersIndexRoute
  AuthenticatedCheckoutInvoicesIndexRoute: typeof AuthenticatedCheckoutInvoicesIndexRoute
  AuthenticatedCheckoutOrderNotesIndexRoute: typeof AuthenticatedCheckoutOrderNotesIndexRoute
  AuthenticatedCheckoutPaymentsIndexRoute: typeof AuthenticatedCheckoutPaymentsIndexRoute
  AuthenticatedCheckoutShipmentsIndexRoute: typeof AuthenticatedCheckoutShipmentsIndexRoute
  AuthenticatedCheckoutShippingMethodsIndexRoute: typeof AuthenticatedCheckoutShippingMethodsIndexRoute
  AuthenticatedNotificationsHistoryIndexRoute: typeof AuthenticatedNotificationsHistoryIndexRoute
  AuthenticatedNotificationsPreferencesIndexRoute: typeof AuthenticatedNotificationsPreferencesIndexRoute
  AuthenticatedOrdersOrderIdIndexRoute: typeof AuthenticatedOrdersOrderIdIndexRoute
  AuthenticatedCatalogCategoriesCategoryIdEditRoute: typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  AuthenticatedCatalogDeliveriesDeliveryIdEditRoute: typeof AuthenticatedCatalogDeliveriesDeliveryIdEditRoute
  AuthenticatedCatalogManufacturersManufacturerIdEditRoute: typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  AuthenticatedCatalogProductsProductIdEditRoute: typeof AuthenticatedCatalogProductsProductIdEditRoute
  AuthenticatedCatalogSuppliersSupplierIdEditRoute: typeof AuthenticatedCatalogSuppliersSupplierIdEditRoute
  AuthenticatedCatalogTagsTagIdEditRoute: typeof AuthenticatedCatalogTagsTagIdEditRoute
  AuthenticatedCheckoutCouponsCouponIdEditRoute: typeof AuthenticatedCheckoutCouponsCouponIdEditRoute
  AuthenticatedCheckoutCouriersCourierIdEditRoute: typeof AuthenticatedCheckoutCouriersCourierIdEditRoute
  AuthenticatedCheckoutOrderNotesNoteIdEditRoute: typeof AuthenticatedCheckoutOrderNotesNoteIdEditRoute
  AuthenticatedCheckoutShipmentsShipmentIdEditRoute: typeof AuthenticatedCheckoutShipmentsShipmentIdEditRoute
  AuthenticatedCheckoutShippingMethodsMethodIdEditRoute: typeof AuthenticatedCheckoutShippingMethodsMethodIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAddressesNewRoute: AuthenticatedAddressesNewRoute,
  AuthenticatedCountriesNewRoute: AuthenticatedCountriesNewRoute,
  AuthenticatedInvoiceTemplatesNewRoute: AuthenticatedInvoiceTemplatesNewRoute,
  AuthenticatedAddressesIndexRoute: AuthenticatedAddressesIndexRoute,
  AuthenticatedCountriesIndexRoute: AuthenticatedCountriesIndexRoute,
  AuthenticatedInvoiceTemplatesIndexRoute:
    AuthenticatedInvoiceTemplatesIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProfilesIndexRoute: AuthenticatedProfilesIndexRoute,
  AuthenticatedAddressesAddressIdEditRoute:
    AuthenticatedAddressesAddressIdEditRoute,
  AuthenticatedCatalogCategoriesNewRoute:
    AuthenticatedCatalogCategoriesNewRoute,
  AuthenticatedCatalogDeliveriesNewRoute:
    AuthenticatedCatalogDeliveriesNewRoute,
  AuthenticatedCatalogManufacturersNewRoute:
    AuthenticatedCatalogManufacturersNewRoute,
  AuthenticatedCatalogProductsNewRoute: AuthenticatedCatalogProductsNewRoute,
  AuthenticatedCatalogSuppliersNewRoute: AuthenticatedCatalogSuppliersNewRoute,
  AuthenticatedCatalogTagsNewRoute: AuthenticatedCatalogTagsNewRoute,
  AuthenticatedCheckoutCouponsNewRoute: AuthenticatedCheckoutCouponsNewRoute,
  AuthenticatedCheckoutCouriersNewRoute: AuthenticatedCheckoutCouriersNewRoute,
  AuthenticatedCheckoutOrderNotesNewRoute:
    AuthenticatedCheckoutOrderNotesNewRoute,
  AuthenticatedCheckoutShippingMethodsNewRoute:
    AuthenticatedCheckoutShippingMethodsNewRoute,
  AuthenticatedCountriesCountryIdEditRoute:
    AuthenticatedCountriesCountryIdEditRoute,
  AuthenticatedInvoiceTemplatesTemplateIdEditRoute:
    AuthenticatedInvoiceTemplatesTemplateIdEditRoute,
  AuthenticatedProfilesProfileIdEditRoute:
    AuthenticatedProfilesProfileIdEditRoute,
  AuthenticatedCatalogCategoriesIndexRoute:
    AuthenticatedCatalogCategoriesIndexRoute,
  AuthenticatedCatalogDeliveriesIndexRoute:
    AuthenticatedCatalogDeliveriesIndexRoute,
  AuthenticatedCatalogManufacturersIndexRoute:
    AuthenticatedCatalogManufacturersIndexRoute,
  AuthenticatedCatalogProductsIndexRoute:
    AuthenticatedCatalogProductsIndexRoute,
  AuthenticatedCatalogSuppliersIndexRoute:
    AuthenticatedCatalogSuppliersIndexRoute,
  AuthenticatedCatalogTagsIndexRoute: AuthenticatedCatalogTagsIndexRoute,
  AuthenticatedCheckoutCouponRedemptionsIndexRoute:
    AuthenticatedCheckoutCouponRedemptionsIndexRoute,
  AuthenticatedCheckoutCouponsIndexRoute:
    AuthenticatedCheckoutCouponsIndexRoute,
  AuthenticatedCheckoutCouriersIndexRoute:
    AuthenticatedCheckoutCouriersIndexRoute,
  AuthenticatedCheckoutInvoicesIndexRoute:
    AuthenticatedCheckoutInvoicesIndexRoute,
  AuthenticatedCheckoutOrderNotesIndexRoute:
    AuthenticatedCheckoutOrderNotesIndexRoute,
  AuthenticatedCheckoutPaymentsIndexRoute:
    AuthenticatedCheckoutPaymentsIndexRoute,
  AuthenticatedCheckoutShipmentsIndexRoute:
    AuthenticatedCheckoutShipmentsIndexRoute,
  AuthenticatedCheckoutShippingMethodsIndexRoute:
    AuthenticatedCheckoutShippingMethodsIndexRoute,
  AuthenticatedNotificationsHistoryIndexRoute:
    AuthenticatedNotificationsHistoryIndexRoute,
  AuthenticatedNotificationsPreferencesIndexRoute:
    AuthenticatedNotificationsPreferencesIndexRoute,
  AuthenticatedOrdersOrderIdIndexRoute: AuthenticatedOrdersOrderIdIndexRoute,
  AuthenticatedCatalogCategoriesCategoryIdEditRoute:
    AuthenticatedCatalogCategoriesCategoryIdEditRoute,
  AuthenticatedCatalogDeliveriesDeliveryIdEditRoute:
    AuthenticatedCatalogDeliveriesDeliveryIdEditRoute,
  AuthenticatedCatalogManufacturersManufacturerIdEditRoute:
    AuthenticatedCatalogManufacturersManufacturerIdEditRoute,
  AuthenticatedCatalogProductsProductIdEditRoute:
    AuthenticatedCatalogProductsProductIdEditRoute,
  AuthenticatedCatalogSuppliersSupplierIdEditRoute:
    AuthenticatedCatalogSuppliersSupplierIdEditRoute,
  AuthenticatedCatalogTagsTagIdEditRoute:
    AuthenticatedCatalogTagsTagIdEditRoute,
  AuthenticatedCheckoutCouponsCouponIdEditRoute:
    AuthenticatedCheckoutCouponsCouponIdEditRoute,
  AuthenticatedCheckoutCouriersCourierIdEditRoute:
    AuthenticatedCheckoutCouriersCourierIdEditRoute,
  AuthenticatedCheckoutOrderNotesNoteIdEditRoute:
    AuthenticatedCheckoutOrderNotesNoteIdEditRoute,
  AuthenticatedCheckoutShipmentsShipmentIdEditRoute:
    AuthenticatedCheckoutShipmentsShipmentIdEditRoute,
  AuthenticatedCheckoutShippingMethodsMethodIdEditRoute:
    AuthenticatedCheckoutShippingMethodsMethodIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
