/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfilesIndexRouteImport } from './routes/_authenticated/profiles/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedInvoiceTemplatesIndexRouteImport } from './routes/_authenticated/invoice-templates/index'
import { Route as AuthenticatedCountriesIndexRouteImport } from './routes/_authenticated/countries/index'
import { Route as AuthenticatedAddressesIndexRouteImport } from './routes/_authenticated/addresses/index'
import { Route as AuthenticatedProfilesNewRouteImport } from './routes/_authenticated/profiles/new'
import { Route as AuthenticatedInvoiceTemplatesNewRouteImport } from './routes/_authenticated/invoice-templates/new'
import { Route as AuthenticatedCountriesNewRouteImport } from './routes/_authenticated/countries/new'
import { Route as AuthenticatedAddressesNewRouteImport } from './routes/_authenticated/addresses/new'
import { Route as AuthenticatedCatalogTagsIndexRouteImport } from './routes/_authenticated/catalog/tags/index'
import { Route as AuthenticatedCatalogProductsIndexRouteImport } from './routes/_authenticated/catalog/products/index'
import { Route as AuthenticatedCatalogManufacturersIndexRouteImport } from './routes/_authenticated/catalog/manufacturers/index'
import { Route as AuthenticatedCatalogCategoriesIndexRouteImport } from './routes/_authenticated/catalog/categories/index'
import { Route as AuthenticatedProfilesProfileIdEditRouteImport } from './routes/_authenticated/profiles/$profileId/edit'
import { Route as AuthenticatedInvoiceTemplatesTemplateIdEditRouteImport } from './routes/_authenticated/invoice-templates/$templateId/edit'
import { Route as AuthenticatedCountriesCountryIdEditRouteImport } from './routes/_authenticated/countries/$countryId/edit'
import { Route as AuthenticatedCatalogTagsNewRouteImport } from './routes/_authenticated/catalog/tags/new'
import { Route as AuthenticatedCatalogProductsNewRouteImport } from './routes/_authenticated/catalog/products/new'
import { Route as AuthenticatedCatalogManufacturersNewRouteImport } from './routes/_authenticated/catalog/manufacturers/new'
import { Route as AuthenticatedCatalogCategoriesNewRouteImport } from './routes/_authenticated/catalog/categories/new'
import { Route as AuthenticatedAddressesAddressIdEditRouteImport } from './routes/_authenticated/addresses/$addressId/edit'
import { Route as AuthenticatedCatalogTagsTagIdEditRouteImport } from './routes/_authenticated/catalog/tags/$tagId/edit'
import { Route as AuthenticatedCatalogProductsProductIdEditRouteImport } from './routes/_authenticated/catalog/products/$productId/edit'
import { Route as AuthenticatedCatalogManufacturersManufacturerIdEditRouteImport } from './routes/_authenticated/catalog/manufacturers/$manufacturerId/edit'
import { Route as AuthenticatedCatalogCategoriesCategoryIdEditRouteImport } from './routes/_authenticated/catalog/categories/$categoryId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilesIndexRoute =
  AuthenticatedProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTemplatesIndexRoute =
  AuthenticatedInvoiceTemplatesIndexRouteImport.update({
    id: '/invoice-templates/',
    path: '/invoice-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesIndexRoute =
  AuthenticatedCountriesIndexRouteImport.update({
    id: '/countries/',
    path: '/countries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressesIndexRoute =
  AuthenticatedAddressesIndexRouteImport.update({
    id: '/addresses/',
    path: '/addresses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesNewRoute =
  AuthenticatedProfilesNewRouteImport.update({
    id: '/profiles/new',
    path: '/profiles/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTemplatesNewRoute =
  AuthenticatedInvoiceTemplatesNewRouteImport.update({
    id: '/invoice-templates/new',
    path: '/invoice-templates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesNewRoute =
  AuthenticatedCountriesNewRouteImport.update({
    id: '/countries/new',
    path: '/countries/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressesNewRoute =
  AuthenticatedAddressesNewRouteImport.update({
    id: '/addresses/new',
    path: '/addresses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogTagsIndexRoute =
  AuthenticatedCatalogTagsIndexRouteImport.update({
    id: '/catalog/tags/',
    path: '/catalog/tags/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProductsIndexRoute =
  AuthenticatedCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersIndexRoute =
  AuthenticatedCatalogManufacturersIndexRouteImport.update({
    id: '/catalog/manufacturers/',
    path: '/catalog/manufacturers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesIndexRoute =
  AuthenticatedCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdEditRoute =
  AuthenticatedProfilesProfileIdEditRouteImport.update({
    id: '/profiles/$profileId/edit',
    path: '/profiles/$profileId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTemplatesTemplateIdEditRoute =
  AuthenticatedInvoiceTemplatesTemplateIdEditRouteImport.update({
    id: '/invoice-templates/$templateId/edit',
    path: '/invoice-templates/$templateId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesCountryIdEditRoute =
  AuthenticatedCountriesCountryIdEditRouteImport.update({
    id: '/countries/$countryId/edit',
    path: '/countries/$countryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogTagsNewRoute =
  AuthenticatedCatalogTagsNewRouteImport.update({
    id: '/catalog/tags/new',
    path: '/catalog/tags/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProductsNewRoute =
  AuthenticatedCatalogProductsNewRouteImport.update({
    id: '/catalog/products/new',
    path: '/catalog/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersNewRoute =
  AuthenticatedCatalogManufacturersNewRouteImport.update({
    id: '/catalog/manufacturers/new',
    path: '/catalog/manufacturers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesNewRoute =
  AuthenticatedCatalogCategoriesNewRouteImport.update({
    id: '/catalog/categories/new',
    path: '/catalog/categories/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressesAddressIdEditRoute =
  AuthenticatedAddressesAddressIdEditRouteImport.update({
    id: '/addresses/$addressId/edit',
    path: '/addresses/$addressId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogTagsTagIdEditRoute =
  AuthenticatedCatalogTagsTagIdEditRouteImport.update({
    id: '/catalog/tags/$tagId/edit',
    path: '/catalog/tags/$tagId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogProductsProductIdEditRoute =
  AuthenticatedCatalogProductsProductIdEditRouteImport.update({
    id: '/catalog/products/$productId/edit',
    path: '/catalog/products/$productId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersManufacturerIdEditRoute =
  AuthenticatedCatalogManufacturersManufacturerIdEditRouteImport.update({
    id: '/catalog/manufacturers/$manufacturerId/edit',
    path: '/catalog/manufacturers/$manufacturerId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogCategoriesCategoryIdEditRoute =
  AuthenticatedCatalogCategoriesCategoryIdEditRouteImport.update({
    id: '/catalog/categories/$categoryId/edit',
    path: '/catalog/categories/$categoryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/addresses/new': typeof AuthenticatedAddressesNewRoute
  '/countries/new': typeof AuthenticatedCountriesNewRoute
  '/invoice-templates/new': typeof AuthenticatedInvoiceTemplatesNewRoute
  '/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/addresses': typeof AuthenticatedAddressesIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/invoice-templates': typeof AuthenticatedInvoiceTemplatesIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/addresses/$addressId/edit': typeof AuthenticatedAddressesAddressIdEditRoute
  '/catalog/categories/new': typeof AuthenticatedCatalogCategoriesNewRoute
  '/catalog/manufacturers/new': typeof AuthenticatedCatalogManufacturersNewRoute
  '/catalog/products/new': typeof AuthenticatedCatalogProductsNewRoute
  '/catalog/tags/new': typeof AuthenticatedCatalogTagsNewRoute
  '/countries/$countryId/edit': typeof AuthenticatedCountriesCountryIdEditRoute
  '/invoice-templates/$templateId/edit': typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  '/profiles/$profileId/edit': typeof AuthenticatedProfilesProfileIdEditRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/catalog/manufacturers': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/tags': typeof AuthenticatedCatalogTagsIndexRoute
  '/catalog/categories/$categoryId/edit': typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  '/catalog/manufacturers/$manufacturerId/edit': typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  '/catalog/products/$productId/edit': typeof AuthenticatedCatalogProductsProductIdEditRoute
  '/catalog/tags/$tagId/edit': typeof AuthenticatedCatalogTagsTagIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/addresses/new': typeof AuthenticatedAddressesNewRoute
  '/countries/new': typeof AuthenticatedCountriesNewRoute
  '/invoice-templates/new': typeof AuthenticatedInvoiceTemplatesNewRoute
  '/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/addresses': typeof AuthenticatedAddressesIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/invoice-templates': typeof AuthenticatedInvoiceTemplatesIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/addresses/$addressId/edit': typeof AuthenticatedAddressesAddressIdEditRoute
  '/catalog/categories/new': typeof AuthenticatedCatalogCategoriesNewRoute
  '/catalog/manufacturers/new': typeof AuthenticatedCatalogManufacturersNewRoute
  '/catalog/products/new': typeof AuthenticatedCatalogProductsNewRoute
  '/catalog/tags/new': typeof AuthenticatedCatalogTagsNewRoute
  '/countries/$countryId/edit': typeof AuthenticatedCountriesCountryIdEditRoute
  '/invoice-templates/$templateId/edit': typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  '/profiles/$profileId/edit': typeof AuthenticatedProfilesProfileIdEditRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/catalog/manufacturers': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/tags': typeof AuthenticatedCatalogTagsIndexRoute
  '/catalog/categories/$categoryId/edit': typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  '/catalog/manufacturers/$manufacturerId/edit': typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  '/catalog/products/$productId/edit': typeof AuthenticatedCatalogProductsProductIdEditRoute
  '/catalog/tags/$tagId/edit': typeof AuthenticatedCatalogTagsTagIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/addresses/new': typeof AuthenticatedAddressesNewRoute
  '/_authenticated/countries/new': typeof AuthenticatedCountriesNewRoute
  '/_authenticated/invoice-templates/new': typeof AuthenticatedInvoiceTemplatesNewRoute
  '/_authenticated/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/_authenticated/addresses/': typeof AuthenticatedAddressesIndexRoute
  '/_authenticated/countries/': typeof AuthenticatedCountriesIndexRoute
  '/_authenticated/invoice-templates/': typeof AuthenticatedInvoiceTemplatesIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/_authenticated/addresses/$addressId/edit': typeof AuthenticatedAddressesAddressIdEditRoute
  '/_authenticated/catalog/categories/new': typeof AuthenticatedCatalogCategoriesNewRoute
  '/_authenticated/catalog/manufacturers/new': typeof AuthenticatedCatalogManufacturersNewRoute
  '/_authenticated/catalog/products/new': typeof AuthenticatedCatalogProductsNewRoute
  '/_authenticated/catalog/tags/new': typeof AuthenticatedCatalogTagsNewRoute
  '/_authenticated/countries/$countryId/edit': typeof AuthenticatedCountriesCountryIdEditRoute
  '/_authenticated/invoice-templates/$templateId/edit': typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  '/_authenticated/profiles/$profileId/edit': typeof AuthenticatedProfilesProfileIdEditRoute
  '/_authenticated/catalog/categories/': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/_authenticated/catalog/manufacturers/': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/_authenticated/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/_authenticated/catalog/tags/': typeof AuthenticatedCatalogTagsIndexRoute
  '/_authenticated/catalog/categories/$categoryId/edit': typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  '/_authenticated/catalog/manufacturers/$manufacturerId/edit': typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  '/_authenticated/catalog/products/$productId/edit': typeof AuthenticatedCatalogProductsProductIdEditRoute
  '/_authenticated/catalog/tags/$tagId/edit': typeof AuthenticatedCatalogTagsTagIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/addresses/new'
    | '/countries/new'
    | '/invoice-templates/new'
    | '/profiles/new'
    | '/addresses'
    | '/countries'
    | '/invoice-templates'
    | '/orders'
    | '/profiles'
    | '/addresses/$addressId/edit'
    | '/catalog/categories/new'
    | '/catalog/manufacturers/new'
    | '/catalog/products/new'
    | '/catalog/tags/new'
    | '/countries/$countryId/edit'
    | '/invoice-templates/$templateId/edit'
    | '/profiles/$profileId/edit'
    | '/catalog/categories'
    | '/catalog/manufacturers'
    | '/catalog/products'
    | '/catalog/tags'
    | '/catalog/categories/$categoryId/edit'
    | '/catalog/manufacturers/$manufacturerId/edit'
    | '/catalog/products/$productId/edit'
    | '/catalog/tags/$tagId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/addresses/new'
    | '/countries/new'
    | '/invoice-templates/new'
    | '/profiles/new'
    | '/addresses'
    | '/countries'
    | '/invoice-templates'
    | '/orders'
    | '/profiles'
    | '/addresses/$addressId/edit'
    | '/catalog/categories/new'
    | '/catalog/manufacturers/new'
    | '/catalog/products/new'
    | '/catalog/tags/new'
    | '/countries/$countryId/edit'
    | '/invoice-templates/$templateId/edit'
    | '/profiles/$profileId/edit'
    | '/catalog/categories'
    | '/catalog/manufacturers'
    | '/catalog/products'
    | '/catalog/tags'
    | '/catalog/categories/$categoryId/edit'
    | '/catalog/manufacturers/$manufacturerId/edit'
    | '/catalog/products/$productId/edit'
    | '/catalog/tags/$tagId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/addresses/new'
    | '/_authenticated/countries/new'
    | '/_authenticated/invoice-templates/new'
    | '/_authenticated/profiles/new'
    | '/_authenticated/addresses/'
    | '/_authenticated/countries/'
    | '/_authenticated/invoice-templates/'
    | '/_authenticated/orders/'
    | '/_authenticated/profiles/'
    | '/_authenticated/addresses/$addressId/edit'
    | '/_authenticated/catalog/categories/new'
    | '/_authenticated/catalog/manufacturers/new'
    | '/_authenticated/catalog/products/new'
    | '/_authenticated/catalog/tags/new'
    | '/_authenticated/countries/$countryId/edit'
    | '/_authenticated/invoice-templates/$templateId/edit'
    | '/_authenticated/profiles/$profileId/edit'
    | '/_authenticated/catalog/categories/'
    | '/_authenticated/catalog/manufacturers/'
    | '/_authenticated/catalog/products/'
    | '/_authenticated/catalog/tags/'
    | '/_authenticated/catalog/categories/$categoryId/edit'
    | '/_authenticated/catalog/manufacturers/$manufacturerId/edit'
    | '/_authenticated/catalog/products/$productId/edit'
    | '/_authenticated/catalog/tags/$tagId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/': {
      id: '/_authenticated/profiles/'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice-templates/': {
      id: '/_authenticated/invoice-templates/'
      path: '/invoice-templates'
      fullPath: '/invoice-templates'
      preLoaderRoute: typeof AuthenticatedInvoiceTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/': {
      id: '/_authenticated/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedCountriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addresses/': {
      id: '/_authenticated/addresses/'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/new': {
      id: '/_authenticated/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof AuthenticatedProfilesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice-templates/new': {
      id: '/_authenticated/invoice-templates/new'
      path: '/invoice-templates/new'
      fullPath: '/invoice-templates/new'
      preLoaderRoute: typeof AuthenticatedInvoiceTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/new': {
      id: '/_authenticated/countries/new'
      path: '/countries/new'
      fullPath: '/countries/new'
      preLoaderRoute: typeof AuthenticatedCountriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addresses/new': {
      id: '/_authenticated/addresses/new'
      path: '/addresses/new'
      fullPath: '/addresses/new'
      preLoaderRoute: typeof AuthenticatedAddressesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/tags/': {
      id: '/_authenticated/catalog/tags/'
      path: '/catalog/tags'
      fullPath: '/catalog/tags'
      preLoaderRoute: typeof AuthenticatedCatalogTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/products/': {
      id: '/_authenticated/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof AuthenticatedCatalogProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/': {
      id: '/_authenticated/catalog/manufacturers/'
      path: '/catalog/manufacturers'
      fullPath: '/catalog/manufacturers'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories/': {
      id: '/_authenticated/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/edit': {
      id: '/_authenticated/profiles/$profileId/edit'
      path: '/profiles/$profileId/edit'
      fullPath: '/profiles/$profileId/edit'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice-templates/$templateId/edit': {
      id: '/_authenticated/invoice-templates/$templateId/edit'
      path: '/invoice-templates/$templateId/edit'
      fullPath: '/invoice-templates/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedInvoiceTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/$countryId/edit': {
      id: '/_authenticated/countries/$countryId/edit'
      path: '/countries/$countryId/edit'
      fullPath: '/countries/$countryId/edit'
      preLoaderRoute: typeof AuthenticatedCountriesCountryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/tags/new': {
      id: '/_authenticated/catalog/tags/new'
      path: '/catalog/tags/new'
      fullPath: '/catalog/tags/new'
      preLoaderRoute: typeof AuthenticatedCatalogTagsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/products/new': {
      id: '/_authenticated/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/catalog/products/new'
      preLoaderRoute: typeof AuthenticatedCatalogProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/new': {
      id: '/_authenticated/catalog/manufacturers/new'
      path: '/catalog/manufacturers/new'
      fullPath: '/catalog/manufacturers/new'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories/new': {
      id: '/_authenticated/catalog/categories/new'
      path: '/catalog/categories/new'
      fullPath: '/catalog/categories/new'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addresses/$addressId/edit': {
      id: '/_authenticated/addresses/$addressId/edit'
      path: '/addresses/$addressId/edit'
      fullPath: '/addresses/$addressId/edit'
      preLoaderRoute: typeof AuthenticatedAddressesAddressIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/tags/$tagId/edit': {
      id: '/_authenticated/catalog/tags/$tagId/edit'
      path: '/catalog/tags/$tagId/edit'
      fullPath: '/catalog/tags/$tagId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogTagsTagIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/products/$productId/edit': {
      id: '/_authenticated/catalog/products/$productId/edit'
      path: '/catalog/products/$productId/edit'
      fullPath: '/catalog/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/$manufacturerId/edit': {
      id: '/_authenticated/catalog/manufacturers/$manufacturerId/edit'
      path: '/catalog/manufacturers/$manufacturerId/edit'
      fullPath: '/catalog/manufacturers/$manufacturerId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersManufacturerIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/categories/$categoryId/edit': {
      id: '/_authenticated/catalog/categories/$categoryId/edit'
      path: '/catalog/categories/$categoryId/edit'
      fullPath: '/catalog/categories/$categoryId/edit'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAddressesNewRoute: typeof AuthenticatedAddressesNewRoute
  AuthenticatedCountriesNewRoute: typeof AuthenticatedCountriesNewRoute
  AuthenticatedInvoiceTemplatesNewRoute: typeof AuthenticatedInvoiceTemplatesNewRoute
  AuthenticatedProfilesNewRoute: typeof AuthenticatedProfilesNewRoute
  AuthenticatedAddressesIndexRoute: typeof AuthenticatedAddressesIndexRoute
  AuthenticatedCountriesIndexRoute: typeof AuthenticatedCountriesIndexRoute
  AuthenticatedInvoiceTemplatesIndexRoute: typeof AuthenticatedInvoiceTemplatesIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProfilesIndexRoute: typeof AuthenticatedProfilesIndexRoute
  AuthenticatedAddressesAddressIdEditRoute: typeof AuthenticatedAddressesAddressIdEditRoute
  AuthenticatedCatalogCategoriesNewRoute: typeof AuthenticatedCatalogCategoriesNewRoute
  AuthenticatedCatalogManufacturersNewRoute: typeof AuthenticatedCatalogManufacturersNewRoute
  AuthenticatedCatalogProductsNewRoute: typeof AuthenticatedCatalogProductsNewRoute
  AuthenticatedCatalogTagsNewRoute: typeof AuthenticatedCatalogTagsNewRoute
  AuthenticatedCountriesCountryIdEditRoute: typeof AuthenticatedCountriesCountryIdEditRoute
  AuthenticatedInvoiceTemplatesTemplateIdEditRoute: typeof AuthenticatedInvoiceTemplatesTemplateIdEditRoute
  AuthenticatedProfilesProfileIdEditRoute: typeof AuthenticatedProfilesProfileIdEditRoute
  AuthenticatedCatalogCategoriesIndexRoute: typeof AuthenticatedCatalogCategoriesIndexRoute
  AuthenticatedCatalogManufacturersIndexRoute: typeof AuthenticatedCatalogManufacturersIndexRoute
  AuthenticatedCatalogProductsIndexRoute: typeof AuthenticatedCatalogProductsIndexRoute
  AuthenticatedCatalogTagsIndexRoute: typeof AuthenticatedCatalogTagsIndexRoute
  AuthenticatedCatalogCategoriesCategoryIdEditRoute: typeof AuthenticatedCatalogCategoriesCategoryIdEditRoute
  AuthenticatedCatalogManufacturersManufacturerIdEditRoute: typeof AuthenticatedCatalogManufacturersManufacturerIdEditRoute
  AuthenticatedCatalogProductsProductIdEditRoute: typeof AuthenticatedCatalogProductsProductIdEditRoute
  AuthenticatedCatalogTagsTagIdEditRoute: typeof AuthenticatedCatalogTagsTagIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAddressesNewRoute: AuthenticatedAddressesNewRoute,
  AuthenticatedCountriesNewRoute: AuthenticatedCountriesNewRoute,
  AuthenticatedInvoiceTemplatesNewRoute: AuthenticatedInvoiceTemplatesNewRoute,
  AuthenticatedProfilesNewRoute: AuthenticatedProfilesNewRoute,
  AuthenticatedAddressesIndexRoute: AuthenticatedAddressesIndexRoute,
  AuthenticatedCountriesIndexRoute: AuthenticatedCountriesIndexRoute,
  AuthenticatedInvoiceTemplatesIndexRoute:
    AuthenticatedInvoiceTemplatesIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProfilesIndexRoute: AuthenticatedProfilesIndexRoute,
  AuthenticatedAddressesAddressIdEditRoute:
    AuthenticatedAddressesAddressIdEditRoute,
  AuthenticatedCatalogCategoriesNewRoute:
    AuthenticatedCatalogCategoriesNewRoute,
  AuthenticatedCatalogManufacturersNewRoute:
    AuthenticatedCatalogManufacturersNewRoute,
  AuthenticatedCatalogProductsNewRoute: AuthenticatedCatalogProductsNewRoute,
  AuthenticatedCatalogTagsNewRoute: AuthenticatedCatalogTagsNewRoute,
  AuthenticatedCountriesCountryIdEditRoute:
    AuthenticatedCountriesCountryIdEditRoute,
  AuthenticatedInvoiceTemplatesTemplateIdEditRoute:
    AuthenticatedInvoiceTemplatesTemplateIdEditRoute,
  AuthenticatedProfilesProfileIdEditRoute:
    AuthenticatedProfilesProfileIdEditRoute,
  AuthenticatedCatalogCategoriesIndexRoute:
    AuthenticatedCatalogCategoriesIndexRoute,
  AuthenticatedCatalogManufacturersIndexRoute:
    AuthenticatedCatalogManufacturersIndexRoute,
  AuthenticatedCatalogProductsIndexRoute:
    AuthenticatedCatalogProductsIndexRoute,
  AuthenticatedCatalogTagsIndexRoute: AuthenticatedCatalogTagsIndexRoute,
  AuthenticatedCatalogCategoriesCategoryIdEditRoute:
    AuthenticatedCatalogCategoriesCategoryIdEditRoute,
  AuthenticatedCatalogManufacturersManufacturerIdEditRoute:
    AuthenticatedCatalogManufacturersManufacturerIdEditRoute,
  AuthenticatedCatalogProductsProductIdEditRoute:
    AuthenticatedCatalogProductsProductIdEditRoute,
  AuthenticatedCatalogTagsTagIdEditRoute:
    AuthenticatedCatalogTagsTagIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
