# Generated by Django 5.2.4 on 2025-08-11 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_notificationpreference_notificationhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpreference",
            name="push_token",
        ),
    ]
