# Generated by Django 5.2.4 on 2025-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_remove_product_catalog_pro_status_1a8990_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="website",
            field=models.CharField(
                blank=True, help_text="Manufacturer website URL", max_length=200
            ),
        ),
    ]
